[package]
name = "oh"
version = "0.0.1"
edition = "2021"
license = "GPL-2.0-or-later"
keywords = ["archlinux", "linux", "installer", "manager", "utility"]
categories = ["command-line-utilities"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/oh"
description = "A archlinux installer and manager"

[dependencies]
argh = "0.1.12"
inquire = "0.7.5"