[package]
name = "arch"
version = "0.0.1"
edition = "2021"
license = "GPL-2.0-or-later"
keywords = ["archlinux","editor","installer","manager","tool"]
categories = ["development-tools"]
readme = "README.md"
authors = ["Willy Micieli"]
repository = "https://github.com/otechdo/arch"
description = "A archlinux installer and manager"

[dependencies]
inquire = { version = "0.7.4", features = ["date", "editor"] }
regex = "1.10.3"
