name: continuous
on:
  push:
    branches: [ "main", "master" , "develop" ]
  pull_request:
    branches: [ "main",  "master" , "develop"]
env:
  CARGO_TERM_COLOR: always
jobs:
  continuous:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: sudo apt-get install -y curl fd-find git packer
    - name: docker
      run:  curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
    - name: rustup
      run:  curl -fsSL https://sh.rustup.rs -o rustup.sh && sudo sh rustup.sh -y
    - name: toolchain
      run:  rustup default stable
    - name: plugins
      run: packer plugins install github.com/hashicorp/docker
    - name: continuous
      run: git clone https://github.com/taishingi/continuous-template.git continuous && cd continuous/rust && ./scripts-gen "github.com" "otechdo" "oh" "${GITHUB_REF##*/}" "4" && packer validate . && packer build .
